[package]
name = "interledger-api"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "API for managing an Interledger node"
license = "Apache-2.0"
edition = "2018"

[dependencies]
futures = "0.1.25"
http = "0.1.16"
interledger-http = { path = "../interledger-http", version = "0.2.1" }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
interledger-spsp = { path = "../interledger-spsp", version = "0.2.1" }
log = "0.4.6"
serde = "1.0.89"
tower-web = "0.3.6"

[badges]
circle-ci = { repository = "emschwartz/interledger-rs" }
codecov = { repository = "emschwartz/interledger-rs" }
